Write-Host "Running Idp"
Start-Process -FilePath "dotnet" -ArgumentList "run" -WorkingDirectory "..\external\Idp\"
Write-Host "Running Api"
Start-Process -FilePath "dotnet" -ArgumentList "run" -WorkingDirectory "..\src\Api\"
Write-Host "Running WebUI"
Start-Process -FilePath "dotnet" -ArgumentList "watch run" -WorkingDirectory "..\src\WebUI\"